repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.7.1
          - "@prettier/plugin-xml@2.2.0"
          - prettier-plugin-svelte@2
      - id: prettier
        files: .(launch|test|world)$
        additional_dependencies:
          - prettier@2.7.1
          - "@prettier/plugin-xml@2.2.0"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--ignore-words-list=ro"]
        exclude: .ipynb|lock.json
