# Launch a ros master with the controller manager and associated services
version: "3.8"

x-base: &base
  build:
    context: .
    dockerfile: docker/Dockerfile.arm64
  image: autobots-visman/reinforcement-learning-arm64:latest

services:
  base: *base
  base-gpu: *base
  gazebo: *base
  moveit-rviz: *base
  state-controller: *base
  img2vec: *base
